---
title: "extract_pathways"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(StarBioTrek)
```

```{r}
species="hsapiens"
pathwaydb="nci"
pathways <- GetData(species, pathwaydb)

#get genes in all pathways + save in file
pathway_ALLGENE <- ConvertedIDgenes(path_ALL=pathways)
pathway_ALLGENE <- pathway_ALLGENE[sort(names(pathway_ALLGENE))]

capture.output(pathway_ALLGENE, file="NCI_Pathways_StarBioTrek_May19_2019.txt")
```

```{r}
# exploratory analysis
gene_symbols <- vector() # list of all genes in pathways of interest
for(pathway_genes in pathway_ALLGENE)
  gene_symbols <- union(gene_symbols, pathway_genes)

gene_symbols <- sort(gene_symbols)

# each row corresponds to a gene, column to pathway
gene_pathway_df <- as.data.frame(matrix(rep(0, length(pathway_ALLGENE)*length(gene_symbols)), 
                                        nrow=length(pathway_ALLGENE)))

rownames(gene_pathway_df) <- names(pathway_ALLGENE)
colnames(gene_pathway_df) <- gene_symbols

for(p in 1:length(pathway_ALLGENE)){
  member_genes <- which(gene_symbols %in% unlist(pathway_ALLGENE[p]))
  gene_pathway_df[p, member_genes] <- 1 # update pathway membership
}
```

```{r}
# Basic statistics
min(sapply(pathway_ALLGENE, length))
max(sapply(pathway_ALLGENE, length))

gene_membership <- sort(colSums(gene_pathway_df), decreasing=T)
head(gene_membership)

pathway_size <- sort(rowSums(gene_pathway_df), decreasing=T)
head(pathway_size)
```

```{r}
# plot histograms of gene and pathway distributions
library(ggplot2)

generate_histogram_from_list <- function(input_list){
  df <- data.frame(values=input_list)
  p <-  ggplot(df, aes(x=values)) +
        geom_histogram(color='black', fill='#ff5252') + 
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.background=element_blank(), axis.line=element_line(), text=element_text(family='Trebuchet MS', face='bold'), axis.title=element_text(size=12), axis.text=element_text(size=13), plot.title=element_text(size = 15, hjust=0.5)) + ylab('Frequency')
  
  return(p)
}
```

```{r}
pg <- generate_histogram_from_list(gene_membership)
pg + ggtitle('Distribution of Gene Membership') + xlab('Number of Pathways') + ylab('Frequency')

pp <- generate_histogram_from_list(pathway_size) 
pp + ggtitle('Distribution of Pathway Size') + xlab('Number of Genes') + ylab('Frequency')
```

```{r}
n_pathways <- nrow(gene_pathway_df)
pathway_pathway_df <- as.data.frame(matrix(rep(0, n_pathways^2), nrow=n_pathways))
pairs <- t(combn(n_pathways, 2))

pathway_pathway_df[1, 1] <- sum(gene_pathway_df[1, ])
for(i in 1:nrow(pairs)){
  pr = pairs[i, ]
  pathway_membership_sum <- gene_pathway_df[pr[1], ] + gene_pathway_df[pr[2], ] # element wise sum of binary vectors
  pathway_pathway_intersection = sum(pathway_membership_sum == 2) # counting number of intersections (~AND operation)

  pathway_pathway_df[pr[1], pr[2]] <- pathway_pathway_intersection # update intersection values
  pathway_pathway_df[pr[2], pr[1]] <- pathway_pathway_intersection
  
  if(pathway_pathway_df[pr[2], pr[2]] == 0)
    pathway_pathway_df[pr[2], pr[2]] <- sum(gene_pathway_df[pr[2], ]) # update diagonal (reflexive) values
  
  if(i %% 100 == 0)
    print(paste(i, " out of ", nrow(pairs), " processed.", sep=""))
}
```

```{r}
# fast statistics on pathway-pathway matrix
sparsity <- (sum(pathway_pathway_df != 0) - nrow(pathway_pathway_df)) / 
            (nrow(pathway_pathway_df)*(ncol(pathway_pathway_df)-1))
print(sparsity)
```

```{r}
# draw a heatmap of pathway-pathway intersections
pathway_pathway_df.m <- pathway_pathway_df
for(i in 1:nrow(pathway_pathway_df.m)) # remove diagonals for visualization purposes (to remove high outlying values in diagonal)
  pathway_pathway_df.m[i, i] <- 0

colnames(pathway_pathway_df.m) <- paste("P", 1:ncol(pathway_pathway_df.m), sep="")
rownames(pathway_pathway_df.m) <- paste("P", 1:nrow(pathway_pathway_df.m), sep="")
pathway_pathway_df.m$pathway_id <- rownames(pathway_pathway_df.m)
pathway_pathway_df.m <- melt(pathway_pathway_df.m)

(p2<-ggplot(pathway_pathway_df.m) + 
    geom_tile(aes(x=variable, y=reorder(pathway_id, 1:nrow(pathway_pathway_df.m), order=T), fill=value), color="white") + 
    scale_fill_gradient(low="white", high="red", name="Intersection") + 
    xlab("Pathways") +
    ylab("Pathways") +
    theme(axis.text=element_text(size=3), text=element_text(family='Trebuchet MS', face='bold')))
```

```{r}
pathway_pathway_df.s <- pathway_pathway_df
for(i in 1:nrow(pathway_pathway_df))
  pathway_pathway_df[i, i] <- 0

pathway_intersections <- rowSums(pathway_pathway_df.s)

pi <- generate_histogram_from_list(pathway_size) 
pi + ggtitle('Distribution of Pathway Intersections') + xlab('Number of Intersections') + ylab('Number of Pathways')
```