---
title: "extract_pathways"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(StarBioTrek)
library(ggplot2)
library(DescTools)
library(reshape2)
source('../../base/plotting.R')
```

```{r}
species="hsapiens"
pathwaydb <- "reactome" #"biocarta" #"nci" #"kegg" 
pathways <- GetData(species, pathwaydb)

# get genes in all pathways + save in file
pathway_ALLGENE <- ConvertedIDgenes(path_ALL=pathways)
pathway_ALLGENE <- pathway_ALLGENE[sort(names(pathway_ALLGENE))]
```

```{r}
capture.output(pathway_ALLGENE, file=paste(pathwaydb, "_Pathways_StarBioTrek_", Sys.Date(), ".txt", sep=""))
```

```{r}
# exploratory analysis
gene_symbols <- vector() # list of all genes in pathways of interest
p <- 1
for(pathway_genes in pathway_ALLGENE){
  if(length(pathway_genes) > 0)
    gene_symbols <- union(gene_symbols, pathway_genes)
  else{
    print(paste(names(pathway_ALLGENE)[p], " removed [empty list].", sep=""))
    pathway_ALLGENE[p] <- NULL
    p <- p-1
  }
    
  p <- p+1
}

gene_symbols <- sort(gene_symbols)
```

```{r}
# each row corresponds to a gene, column to pathway
pathway_gene_df <- as.data.frame(matrix(rep(0, length(pathway_ALLGENE)*length(gene_symbols)), 
                                        nrow=length(pathway_ALLGENE)))

rownames(pathway_gene_df) <- names(pathway_ALLGENE)
colnames(pathway_gene_df) <- gene_symbols

for(p in 1:length(pathway_ALLGENE)){
  member_genes <- which(gene_symbols %in% unlist(pathway_ALLGENE[p]))
  pathway_gene_df[p, member_genes] <- 1 # update pathway membership
}

# write matrix to file
write.table(pathway_gene_df, file=paste(pathwaydb, "_pathway_gene_matrix_", Sys.Date(), ".txt", sep=""), row.names=T, col.names=T, quote=F)

# write features (gene,n_pathways) to file
gene_pathway_membership <- as.data.frame(colSums(pathway_gene_df))
gene_pathway_membership[, 2] <- gene_pathway_membership[, 1]
gene_pathway_membership[, 1] <- rownames(gene_pathway_membership)
colnames(gene_pathway_membership) <- c("gene", "n_pathways")
write.table(gene_pathway_membership, file=paste(pathwaydb, "_gene_membership", ".txt", sep=""), row.names=F, col.names=T, quote=F, sep=",")
```

```{r}
# Basic statistics
length(pathway_ALLGENE)
length(gene_symbols)

min(sapply(pathway_ALLGENE, length))
max(sapply(pathway_ALLGENE, length))

pathway_size <- sort(rowSums(pathway_gene_df), decreasing=T)
tail(pathway_size, 1)
head(pathway_size, 1)

gene_membership <- sort(colSums(pathway_gene_df), decreasing=T)
tail(gene_membership, 1)
head(gene_membership, 1)
```

```{r}
pg <- generate_histogram_from_list(gene_membership)
pg + ggtitle('Distribution of Gene Membership') + xlab('Number of Pathways') + ylab('Frequency')

pp <- generate_histogram_from_list(pathway_size) 
pp + ggtitle('Distribution of Pathway Size') + xlab('Number of Genes') + ylab('Frequency') # + xlim(0, 100) # enforce x-axis range
```

```{r}
# Pathway-pathway intersection: Efficiently using PairApply of DescTools
n_pathways <- nrow(pathway_gene_df)

# x and y are two binary vectors (gene membership in pathways)
# PairApply applies pairwise column operations, we use transpose of pathway_gene_df
calc_intersection <- function(x, y){
  pathway_membership_sum <- x+y
  pathway_pathway_intersection <- sum(pathway_membership_sum == 2)
  return(pathway_pathway_intersection)
}

pathway_pathway_df <- as.data.frame(PairApply(t(pathway_gene_df), FUN=calc_intersection))

# write matrix to file
write.table(pathway_pathway_df, file=paste(pathwaydb, "_pathway_pathway_matrix_", Sys.Date(), ".txt", sep=""), row.names=T, col.names=T, quote=F)
```

```{r}
# Pathway-pathway intersection using permutations + for loop for pairwise comparisons; considerably less efficient than the one above 
# n_pathways <- nrow(pathway_gene_df)
# pathway_pathway_df <- as.data.frame(matrix(rep(0, n_pathways^2), nrow=n_pathways))
# pairs <- t(combn(n_pathways, 2))
# 
# pathway_pathway_df[1, 1] <- sum(pathway_gene_df[1, ])
# for(i in 1:nrow(pairs)){
#   pr = pairs[i, ]
#   pathway_membership_sum <- pathway_gene_df[pr[1], ] + pathway_gene_df[pr[2], ] # element wise sum of binary vectors
#   pathway_pathway_intersection <- sum(pathway_membership_sum == 2) # counting number of intersections (~AND operation)
# 
#   pathway_pathway_df[pr[1], pr[2]] <- pathway_pathway_intersection # update intersection values
#   pathway_pathway_df[pr[2], pr[1]] <- pathway_pathway_intersection
#   
#   if(pathway_pathway_df[pr[2], pr[2]] == 0)
#     pathway_pathway_df[pr[2], pr[2]] <- sum(pathway_gene_df[pr[2], ]) # update diagonal (reflexive) values
#   
#   if(i %% 100 == 0)
#     print(paste(i, " out of ", nrow(pairs), " processed.", sep=""))
# }
```

```{r}
# fast statistics on pathway-pathway matrix
sparsity <- (sum(pathway_pathway_df != 0) - nrow(pathway_pathway_df)) / 
            (nrow(pathway_pathway_df)*(ncol(pathway_pathway_df)-1))
print(sparsity)
```

```{r}
# draw a heatmap of pathway-pathway intersections
#pathway_pathway_df.m <- pathway_pathway_df
for(i in 1:nrow(pathway_pathway_df.m)) # remove diagonals for visualization purposes (to remove high outlying values in diagonal)
  pathway_pathway_df.m[i, i] <- 0

colnames(pathway_pathway_df.m) <- paste("P", 1:ncol(pathway_pathway_df.m), sep="")
rownames(pathway_pathway_df.m) <- paste("P", 1:nrow(pathway_pathway_df.m), sep="")
pathway_pathway_df.m$pathway_id <- rownames(pathway_pathway_df.m)
pathway_pathway_df.m <- melt(pathway_pathway_df.m)

(p2<-ggplot(pathway_pathway_df.m) + 
    geom_tile(aes(x=variable, y=reorder(pathway_id, 1:nrow(pathway_pathway_df.m), order=T), fill=value), color="white") + 
    scale_fill_gradient(low="white", high="red", name="Intersection") + 
    xlab("Pathways") +
    ylab("Pathways") +
    theme(axis.text=element_text(size=3), text=element_text(family='Trebuchet MS', face='bold')))
```

```{r}
# distributions of pathway-pathway intersections; exploratory, not used in figure updates
pathway_pathway_df.s <- pathway_pathway_df
for(i in 1:nrow(pathway_pathway_df))
  pathway_pathway_df[i, i] <- 0

pathway_intersections <- rowSums(pathway_pathway_df.s)

pi <- generate_histogram_from_list(pathway_size) 
pi + ggtitle('Distribution of Pathway Intersections') + xlab('Number of Intersections') + ylab('Number of Pathways')
```