---
title: "mobility_lists_analysis"
output: html_document
---

```{r pressure, echo=FALSE}
ppi_networks <- c('STRING', 'HumanNetv2')
cancer_types <- c('BRCA', 'CESC', 'CHOL', 'COAD', 'ESCA', 'HNSC', 'KICH', 'KIRC', 'KIRP', 'LIHC', 'LUAD', 'LUSC', 'PRAD', 'READ', 'STAD', 'THCA', 'UCEC')

variant_type = 'somatic_MC3'

  # Combine with CancerMine to give a bump to known cancer genes
cancerMine_dir <- '../gene_lists/literature/'
cancerMine_filename <- 'cancermine_collated_v24_May2020.tsv'
cancerMine_dictionary_filename <- 'cancermine_dictionary_v24.tsv'

#all_tissues <- c('all', 'blood', 'kidney', 'leg', 'bone', 'arm', 'pancrea', 'uter', 'ovar', 'bone_marrow', 'lymph_node', 'head', 'neck', 'skin', 'thym', 'colo', 'rect', 'stomach', 'liver', 'lung', 'esophag', 'cervix', 'brain', 'bladder', 'testes', 'spinal', 'anus', 'peni', 'saliv', 'mouth', 'thyroid', 'intestine', 'muscle', 'heart', 'uterus', 'prosta', 'eye', 'vulva', 'bile_duct')

tissues <- c('breast', 'lung', 'lung')

input_dir <- 'mobility_lists/whole_lists/'
output_dir <- 'mobility_lists/prioritized_lists/' # directory in which resulting lists are saved

expr_dir <- 'tcga_results/'
depmap_dir <- 'gene_lists/dependency/'
```

```{r}
select_genes <- function(df, mobility_score_threshold=1500, final_rank_threshold=1000){
  sdf <- df[df$mobility_score >= mobility_score_threshold & df$final_rank <= final_rank_threshold, ]
  sdf <- sdf[order(sdf$final_rank), ]
  return(sdf)
}

# returns known genes in gene_list
get_known_genes <- function(gene_list, known_genes){
  intersecting_known_genes <- intersect(gene_list, known_genes)
  if(length(intersecting_known_genes) > 0)
    return(capture.output(cat(intersecting_known_genes, sep=', ')))
  else
    return('None')
}

# returns a vector with integer values 0, -1 and +1; 
# 0 if gene is not differentially expressed; 1 over-expressed, -1 underexpressed
get_expr_vector <- function(input_genes, expr_dir, cancer_type){
  expr_data <- read.table(paste(expr_dir, paste(tolower(cancer_type), 'expression', 'results.csv', sep='_'), sep=''), header=T, stringsAsFactors=F, sep=',') # DE genes
  de_inds <- match(input_genes, expr_data$gene)
  
  expr_vector <- expr_data[de_inds, paste('logFC', tolower(cancer_type), sep='_')]
  expr_vector[is.na(expr_vector)] <- 0
  expr_vector <- sign(expr_vector)
  
  return(expr_vector)
}

# returns a df with 2 cols for ALL genes: minimum score across all cell lines in RNAi and CRISPR screens
calculate_depmap_min_df_all_genes <- function(depmap_dir){
    depmap_filename <- paste(depmap_dir, 'Achilles_gene_effect_all.csv', sep='')
    crispr_depmap_df_all_genes <- read.table(depmap_filename, header=T, stringsAsFactors=F, sep=',')
    crispr_minscores <- apply(crispr_depmap_df_all_genes[, 2:ncol(crispr_depmap_df_all_genes)], 1, min)
    names(crispr_minscores) <- crispr_depmap_df_all_genes[, 'gene']
    
    depmap_filename <- paste(depmap_dir, 'D2_combined_gene_dep_scores_all.csv', sep='')
    rnai_depmap_df_all_genes <- read.table(depmap_filename, header=T, stringsAsFactors=F, sep=',')
    rnai_minscores <- apply(rnai_depmap_df_all_genes[, 2:ncol(rnai_depmap_df_all_genes)], 1, min)
    names(rnai_minscores) <- rnai_depmap_df_all_genes[, 'gene']
    
    all_genes <- union(names(rnai_minscores), names(crispr_minscores))
    depmap_min_df_all_genes <- data.frame(gene=all_genes, min_crispr=crispr_minscores[all_genes], min_rnai=rnai_minscores[all_genes])
    depmap_min_df_all_genes[is.na(depmap_min_df_all_genes)] <- 0
    
    return(depmap_min_df_all_genes)
}

# returns a df with 2 cols for INPUT genes: minimum score across all cell lines in RNAi and CRISPR screens
# for efficiency, it takes entire data frames read by calculate_depmap_min_df as input
get_depmap_min_df <- function(input_genes, depmap_min_df_all_genes){
  depmap_min_df <- depmap_min_df_all_genes[match(input_genes, depmap_min_df_all_genes[, 'gene']), c('min_crispr', 'min_rnai')]
  return(depmap_min_df)
}

# returns a vector with avg depmap score values in cancer_type-specific cell lines
# if gene not in depmap list, value is 0
get_depmap_df <- function(input_genes, depmap_dir, depmap_type, cancer_type){
  depmap_filename <- paste(depmap_dir, 'D2_combined_gene_dep_scores_', cancer_type, '.csv', sep='')
  if(depmap_type == 'crispr')
    depmap_filename <- paste(depmap_dir, 'Achilles_gene_effect_', cancer_type, '.csv', sep='')
  
  if(!file.exists(depmap_filename))
    depmap_filename <- gsub(cancer_type, 'all', depmap_filename)
  
  depmap_data <- read.table(depmap_filename, header=T, stringsAsFactors=F, sep=',')
  depmap_data$p_neg_score <- rowSums(depmap_data < 0) / rowSums(depmap_data != 0) # percentage of cell lines in which each gene has -ve value

  dp_inds <- match(input_genes, depmap_data$gene)

  p_val <- wilcox.test(depmap_data$p_neg_score[dp_inds], depmap_data$p_neg_score[setdiff(1:nrow(depmap_data), dp_inds)], alternative='greater')$p.value # p-value on whether selected genes statistically impact cell survival (i.e. have negative values in a large number of cell lines) more than remaining genes
  print(paste('Mann-Whitney U Test p-value (', depmap_type, '): ', p_val, sep=''))
  
  depmap_df <- depmap_data[dp_inds, c('dep_score', 'p_neg_score')]
  colnames(depmap_df) <- gsub('score', paste('score', depmap_type, sep='_'), colnames(depmap_df))
  
  depmap_df[is.na(depmap_df)] <- 0
  
  return(depmap_df)
}

library(mgsub); library(stats) # replace cancer types to include tissue name
get_cancerMine_vector <- function(input_genes, cancerMine_dir, cancerMine_filename, cancerMine_dictionary_filename, cancer_type){
  cancerMine_data <- read.table(paste(cancerMine_dir, cancerMine_filename, sep=''), header=T, quote="\"", stringsAsFactors=F, fill=T, sep='\t')
  cancerMine_data[, 'cancer_normalized'] <- gsub(' ', '_', cancerMine_data[, 'cancer_normalized'])
  cancerMine_dict <- read.table(paste(cancerMine_dir, cancerMine_dictionary_filename, sep=''), header=T, stringsAsFactors=F, fill=T, sep='\t')

  cancerMine_data$cancer_normalized_w_types <- mgsub(cancerMine_data$cancer_normalized, cancerMine_dict$from, cancerMine_dict$to) # add tissue and cancer types (i.e. could be done once and passed as parameter if speedup is needed)
  cancerMine_data <- cancerMine_data[grepl(cancer_type, cancerMine_data$cancer_normalized_w_types), ] # retain data of cancer type only
  cancerMine_data <- aggregate(cancerMine_data[, c('citation_count')], by=list(gene_normalized=cancerMine_data$gene_normalized), sum) # aggregate data frame
  colnames(cancerMine_data) <- c('gene_normalized', 'citation_count')
    
  cancerMine_vector <- cancerMine_data$citation_count[match(input_genes, cancerMine_data$gene_normalized)]
  cancerMine_vector[is.na(cancerMine_vector)] <- 0

  return(cancerMine_vector)
}
```

```{r}
depmap_min_df_all_genes <- calculate_depmap_min_df_all_genes(depmap_dir) # minumum crispr and rnai depscores for each gene in all cell lines (i.e. not only cancer type-specific ones)
```

```{r}
Bailey_et_al_known_genes_file <- '../gene_lists/known_genes/Bailey_driver_gene_list.csv'
Bailey_et_al_known_genes <- read.table(Bailey_et_al_known_genes_file , header=T, stringsAsFactors=F, sep=',')

for(cti in 1:length(cancer_types)){
  ct <- cancer_types[cti]
  print(paste('==============Cancer type:', ct, sep=' '))
  
  tissue <- tissues[cti]
  
  COSMIC_known_genes_file <- paste(paste('../gene_lists/known_genes/COSMIC_v90_membership', ct, variant_type, sep='_'), 'csv', sep='.')
  ct_COSMIC_known_genes <- read.table(COSMIC_known_genes_file , header=T, stringsAsFactors=F, sep=',')
  ct_Bailey_et_al_known_genes <- Bailey_et_al_known_genes[grepl(ct, Bailey_et_al_known_genes$Cancer),]
  
  for(ppi_networki in 1:length(ppi_networks)){
    ppi_network = ppi_networks[ppi_networki]

    mobility_df = read.table(paste(input_dir, paste(variant_type, ct, ppi_network, 'lcc', tolower(ct), 'mobility_list.csv', sep='_'), sep=''), header=F, col.names=c('gene', 'mobility_score', 'initial_rank', 'final_rank'), stringsAsFactors=F, sep=',')
    
    mobility_threshold <- 0.25*nrow(mobility_df); final_rank_threshold <- 1000 # pick genes that jumped up 25%+ ranks and ended up in top 1000 list
    upward_mobility_genes <- select_genes(mobility_df, mobility_score_threshold=mobility_threshold, final_rank_threshold=final_rank_threshold)
    print(paste('Number of upward mobility genes [ ', ppi_network, ']:', nrow(upward_mobility_genes), sep=' '))
    print(paste('Upward mobility', ct, 'COSMIC known genes:',  get_known_genes(upward_mobility_genes$gene, ct_COSMIC_known_genes$gene)))
    print(paste('Upward mobility', ct, 'Bailey et al. list known genes:',  get_known_genes(upward_mobility_genes$gene, ct_Bailey_et_al_known_genes$Gene)))
    
    upward_mobility_genes$de_expr <- get_expr_vector(upward_mobility_genes$gene, expr_dir, ct) # de genes column added
    
    upward_mobility_genes_dm <- cbind(get_depmap_df(upward_mobility_genes$gene, depmap_dir, 'crispr', ct), get_depmap_df(upward_mobility_genes$gene, depmap_dir, 'rnai', ct)) # avg cancer_type-specific depmap score and ratio of cell types in which the gene's depmap score is -ve, for both crispr and rnai
    upward_mobility_genes <- cbind(upward_mobility_genes, upward_mobility_genes_dm)
    
    upward_mobility_genes_min_dm <- get_depmap_min_df(upward_mobility_genes$gene, depmap_min_df_all_genes) # minimum dp gene scores across all cell lines added
    upward_mobility_genes <- cbind(upward_mobility_genes, upward_mobility_genes_min_dm)
    
    upward_mobility_genes$citation_count <- get_cancerMine_vector(upward_mobility_genes$gene, cancerMine_dir, cancerMine_filename, cancerMine_dictionary_filename, ct) # literature citation count column added 
      
    upward_mobility_filename <- paste(output_dir, paste(variant_type, ct, ppi_network, 'lcc', tolower(ct), 'prioritized_mobility_list.csv', sep='_'), sep='')
    write.table(upward_mobility_genes, upward_mobility_filename, col.names=T, row.names=F, quote=F, sep=',')
      
    # across-ppi intersection lists
    processed_ppi_networks <- capture.output(cat(ppi_networks[1:ppi_networki], sep='-'))
    if(ppi_networki == 1){
      intersection_df <- upward_mobility_genes[, c(1, 5:ncol(upward_mobility_genes))]
    } else{
      intersection_row_inds <- match(upward_mobility_genes$gene, intersection_df$gene)
      intersection_row_inds <- intersection_row_inds[!is.na(intersection_row_inds)] # indices of intersecting genes

      intersection_df <- intersection_df[intersection_row_inds, ]
      
      print(paste('Number of intersecting upward mobility genes [ ', processed_ppi_networks, ']:', nrow(intersection_df), sep=' '))
      print(paste('Upward mobility', ct, 'COSMIC known genes:',  get_known_genes(intersection_df$gene, ct_COSMIC_known_genes$gene)))
      print(paste('Upward mobility', ct, 'Bailey et al. list known genes:',  get_known_genes(intersection_df$gene, ct_Bailey_et_al_known_genes$Gene)))
      
      intersection_filename <- paste(output_dir, paste(variant_type, ct, processed_ppi_networks, 'lcc', tolower(ct), 'prioritized_mobility_list.csv', sep='_'), sep='')
      write.table(intersection_df, intersection_filename, col.names=T, row.names=F, quote=F, sep=',')
    }
  }
}
```
